import { VacationType } from './types';

export const categories = [
  'HR',
  'GameDev',
  'Маркетинг',
  'Video production',
  'Development',
  'Project Manager',
  'Lead разработки',
  'Дизайн',
  'Тестирование',
  'Администрирование',
];




export const vacationsDepartmentsMap = [
  ['3D animator', 'Video production'],
  ['3D Generalist', 'Video production'],
  ['Content creation', 'Video production'],
  ['Motion Designer', 'Video production'],
  ['Backend Developer', 'Development'],
  ['Project Manager (Backend)', 'Project Manager'],
  ['Project Manager', 'Project Manager'],
  ['ML Developer', 'Development'],
  ['IOS Developer', 'Development'],
  ['Unity Developer', 'Development'],
  ['Lead iOS Developer', 'Development'],
  ['Lead Unity Developer', 'Development'],
  ['Graphic / UX/UI Designer', 'Design'],
  ['System Administrator', 'Администрирование'],
  ['Юрист', 'Юридический'],
  ['IT рекрутер', 'HR'],
  ['HR менеджер', 'HR'],
  ['QA специалист', 'QA'],
  ['Jira Administrator', 'Администрирование'],
  ['Маркетолог', 'Маркетинг'],
  ['Помощник маркетолога', 'Маркетинг'],
  ['Контент менеджер', 'Маркетинг'],
  ['Копирайтер', 'Маркетинг'],
  ['Game Designer', 'GameDev'],
  ['Level-Designer', 'GameDev'],
  ['UX/UI дизайнер', 'GameDev'],
  ['3D artist', 'GameDev'],
  ['3D animator', 'GameDev'],
  ['2D artist', 'GameDev'],
  ['2D concept', 'GameDev'],
  ['Unity Developer', 'GameDev'],
];

export const vacationsList = {
  '3D animator': ['Дизайн', 'Development'],
  '3D Generalist': ['Дизайн'],
  'Video Editor': ['Video production'],
  'Motion Designer': ['Дизайн'],
  'Content creation': ['Project manager'],
  Backend: ['Development'],
  'Project Manager': ['Project manager'],
  'Project Manager Backend': ['Project manager'],
  Маркетолог: ['Маркетинг'],
  QA: ['Тестирование'],
  Jira: ['Development'],
  IOS: ['Development'],
  Unity: ['GameDev', 'Development'],
  'TL IOS': ['Development'],
  'TL Unity': ['GameDev'],
  'Script&Director': ['Development', 'Project manager'],
  Recruiter: ['HR'],
  'ML Developer': ['Development'],
  'System Administrator': ['Администрирование', 'Lead разработки'],
  'Graphic designer': ['Дизайн'],
  Lawyer: ['Маркетинг'],
  '3D artist': ['Дизайн'],
  'Ui/Ux дизайнер': ['Дизайн'],
  '2D artist': ['Дизайн'],
  '2D concept': ['Дизайн'],
  'Game designer': ['Дизайн', 'GameDev'],
  'Level-Designer': ['Дизайн'],
};

